# default configuration
baseURL = "http://akarshsingh.com/"
languageCode = "en-us"
title = "Akarsh Singh"
paginate = 10
enableRobotsTXT = true
canonifyURLs = true

# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 2

[[menu.main]]
URL = "blogs"
name = "Blogs"
weight = 3

[[menu.main]]
URL = "projects"
name = "Projects"
weight = 4


# default parameters
[params]
author = "Akarsh Singh"
og_image = ""
sitename = "Akarsh Singh"

# social site
[[params.social]]
URL = "https://github.com/akarshsingh9/"
title = "GitHub"
icon = "ti-github"

[[params.social]]
URL = "https://twitter.com/akarsh_singh9"
title = "Twitter"
icon = "ti-twitter-alt"

[[params.social]]
URL = "https://www.facebook.com/codeinpython/"
title = "Facebook"
icon = "ti-facebook"

