# default configuration
baseURL = "http://akarshsingh.com/"
languageCode = "en-us"
title = "Akarsh Singh"
enableRobotsTXT = true
canonifyURLs = true

[taxonomies]
tag = "tags"

# menu
[menu]
  [[menu.nav]]
  name = "Blog"
  url = "/post/"
  weight = 1.0

  [[menu.nav]]
  name = "Projects"
  url = "/project/"
  weight = 2.0

  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 3.0


# default parameters
[params]
author = "Akarsh Singh"
og_image = ""
sitename = "Akarsh Singh"
showActiveNav = true
dateFormat = "Jan 2, 2006"
footerText = "Follow me on: "

# social site
[[params.social]]
URL = "https://github.com/akarshsingh9/"
title = "GitHub"
icon = "ti-github"

[[params.social]]
URL = "https://twitter.com/akarsh_singh9"
title = "Twitter"
icon = "ti-twitter-alt"

[[params.social]]
URL = "https://www.facebook.com/codeinpython/"
title = "Facebook"
icon = "ti-facebook"
